version: "3"
services:
    product_api:
        image: "productservice"
        volumes:
            - ./ProductService:/app
        ports:
            - "8001:80"
        depends_on:
            - db
    order_api:
        image: "orderservice"
        volumes:
            - ./OrderService:/app
        ports:
            - "8002:80"
        depends_on: 
            - db
    stock_api:
        image: "stockservice"
        volumes:
            - ./StockService:/app
        ports:
            - "8003:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        hostname: 'sqlserver'
        environment:
            SA_PASSWORD: "Truong97"
            ACCEPT_EULA: "Y"