version: "3"
services:
    web:
        image: "peterdinh/bookstore"
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./BookStore:/BookStore
        ports:
            - "8000:8000"
        links:
            - "product_api:productservice"
            - "order_api:orderservice"
            - "stock_api:stockservice"
            
    product_api:
        image: "peterdinh/productservice"
        ports:
            - "8001:80"
        depends_on:
            - db
    order_api:
        image: "peterdinh/orderservice"
        ports:
            - "8002:80"
        depends_on: 
            - db
    stock_api:
        image: "peterdinh/stockservice"
        ports:
            - "8003:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        hostname: 'sqlserver'
        environment:
            SA_PASSWORD: "Truong97"
            ACCEPT_EULA: "Y"