version: "3"
services:
    product_api:
        image: "product"
        ports:
            - "8081:80"
        restart: always
        depends_on:
            - db
    order_api:
        image: "order"
        ports:
            - "8082:80"
        restart: always
        depends_on: 
            - db
    stock_api:
        image: "stock" 
        ports:
            - "8083:80"
        restart: always
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        hostname: 'sqlserver'
        environment:
            SA_PASSWORD: "Truong97"
            ACCEPT_EULA: "Y"
        restart: always