version: "3"
services:
    web:
        image: "bookstore/productservice"
        hostname: 'productservice.com'
        ports:
            - "8081:80"
        restart: always
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        hostname: 'sqlserver'
        environment:
            SA_PASSWORD: "Truong97"
            ACCEPT_EULA: "Y"
        restart: always