version: "3"
services:
    web:
        image: "deftnt/demo_services"
        hostname: 'demo_test.com'
        ports:
            - "8000:80"
        restart: always
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        hostname: 'sqlserver'
        environment:
            SA_PASSWORD: "ThisIsPass1@"
            ACCEPT_EULA: "Y"
        restart: always