from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('manager_account', views.manager_account, name='manager_account'),
    path('see_account', views.see_account, name='see_account'),
    path('manager_rating', views.manager_rating, name='manager_rating'),
    path('see_rating', views.see_rating, name='see_rating'),
    path('manager_order', views.manager_order, name='manager_order'),
    path('see_order', views.see_order, name='see_order'),
    path('manager_category', views.manager_category, name='manager_category'),
    path('add_category', views.add_category, name='add_category'),
    path('edit_category', views.edit_category, name='edit_category'),
    path('manager_product', views.manager_product, name='manager_product'),
    path('add_product', views.add_product, name='add_product'),
    path('edit_product', views.edit_product, name='edit_product'),
    path('add_issue', views.add_issue, name='add_issue'),
    path('manager_issue', views.manager_issue, name='manager_issue'),
    path('edit_issue', views.edit_issue, name='edit_issue'),
    path('manager_receipt', views.manager_receipt, name='manager_receipt'),
    path('add_receipt', views.add_receipt, name='add_receipt'),
    path('edit_receipt', views.edit_receipt, name='edit_receipt'),
    path('manager_stock', views.manager_stock, name='manager_stock'),
    path('add_stock', views.add_stock, name='add_stock'),
    path('edit_stock', views.edit_stock, name='edit_stock'),
    path('setup', views.setup, name='setup'),
]